modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/MoSadie/ExponentialPower/issues"
license="GNU LGPL v3"
logoFile="modIcon.png"
[[mods]]
    modId="exponentialpower"
    version="${file.jarVersion}"
    displayName="Exponential Power"
    updateJSONURL="https://github.com/MoSadie/ExponentialPower/raw/master/update.json"
    displayURL="https://github.com/MoSadie/ExponentialPowerr"
    authors="MoSadie"
    description='''
      Adds generators creating an exponential amount of RF/tick. And some storage blocks to hold that power.
      '''
[[dependencies.exponentialpower]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.exponentialpower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
