name: Build Release

on:
  release:
    types:
    - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew build -Pversion="${{ github.ref_name }}"
    - name: Publish
      uses: Kier-Antipov/mc-publish@v3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

        curseforge-id: 254249
        #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        #modrinth-id:
        #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}